language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ziyakarabudak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ziyakarabudak/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-361828218465"
  bucket_path: "docker-react"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY